# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0209_add_enforcement_actions_filter_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Banner title (internal reference only)')),
            ],
        ),
    ]
