# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0020_rm_formfieldwithbutton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnglishAnswerProxy',
        ),
        migrations.DeleteModel(
            name='SpanishAnswerProxy',
        ),
        migrations.AddField(
            model_name='answerpage',
            name='answer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Categorize this answer. Avoid putting into more than one category.', to='ask_cfpb.Category'),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Check to make this one of two featured answers on the landing page.'),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='featured_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='redirect_to_page',
            field=models.ForeignKey(blank=True, help_text='Choose another AnswerPage to redirect this page to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirect_to_pages', to='ask_cfpb.AnswerPage'),
        ),
        migrations.AddField(
            model_name='answerpage',
            name='related_questions',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Maximum of 3', related_name='related_question', to='ask_cfpb.AnswerPage'),
        ),
    ]
