name: docs

on: 
  push:
    branches:
      - master

jobs:

  publish:
    name: build and publish docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/docs.txt

      - name: Publish docs
        run: mkdocs build

      - name: Publish docs
        run: mkdocs gh-deploy
